In [1]:
from utils.api_2_db import DataSyncer
import pandas as pd
from utils.update_blocks_and_workers import update_blocks_and_live_workers
from utils.update_payment_and_performance import update_payment_and_performance
from utils.update_pool_stats import update_pool_stats
from utils.init_db import init_db

In [4]:
db_sync = DataSyncer(config_path="../conf")
miner = '9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPVApYkk'

In [5]:
init_db()

intializing DB
UPDATED STATS TABLE SUCCESFULLY
UPDATED BLOCK TABLE SUCCESFULLY

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:180: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

Index(['fee', 'paid', 'blocks', 'last_block_found', 'enabled',
       'minimumpayment', 'payoutscheme', 'connectedminers', 'poolhashrate',
       'sharespersecond', 'networktype', 'networkhashrate',
       'networkdifficulty', 'lastnetworkblocktime', 'blockheight',
       'connectedpeers', 'rewardtype', 'pooleffort', 'poolttf', 'price',
       'insert_time_stamp'],
      dtype='object')
no live data for miner 9fGzn8VCszvFMXo2KDrQiVowwSdchVT13ygX26RKUfkjcruRq7J
no live data for miner 9iJkieXSookLtaYr8JZ8A8nKuev9dzRMwxkGjuyQebnQgCj8zdC
UPDATED LIVE WORK, PERFORMANCE, AND PAYMENT TABLES SUCCESFULLY
complete

In [6]:
update_pool_stats()

UPDATED STATS TABLE SUCCESFULLY

In [7]:
update_blocks_and_live_workers()

UPDATED BLOCK TABLE SUCCESFULLY

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:180: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

Index(['fee', 'paid', 'blocks', 'last_block_found', 'enabled',
       'minimumpayment', 'payoutscheme', 'connectedminers', 'poolhashrate',
       'sharespersecond', 'networktype', 'networkhashrate',
       'networkdifficulty', 'lastnetworkblocktime', 'blockheight',
       'connectedpeers', 'rewardtype', 'pooleffort', 'poolttf', 'price',
       'insert_time_stamp'],
      dtype='object')
no live data for miner 9fGzn8VCszvFMXo2KDrQiVowwSdchVT13ygX26RKUfkjcruRq7J
no live data for miner 9iJkieXSookLtaYr8JZ8A8nKuev9dzRMwxkGjuyQebnQgCj8zdC
UPDATED LIVE WORK, PERFORMANCE, AND PAYMENT TABLES SUCCESFULLY

In [8]:
update_payment_and_performance()

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:180: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

Index(['fee', 'paid', 'blocks', 'last_block_found', 'enabled',
       'minimumpayment', 'payoutscheme', 'connectedminers', 'poolhashrate',
       'sharespersecond', 'networktype', 'networkhashrate',
       'networkdifficulty', 'lastnetworkblocktime', 'blockheight',
       'connectedpeers', 'rewardtype', 'pooleffort', 'poolttf', 'price',
       'insert_time_stamp'],
      dtype='object')
UPDATED LIVE WORK, PERFORMANCE, AND PAYMENT TABLES SUCCESFULLY

In [9]:
update_pool_stats()

UPDATED STATS TABLE SUCCESFULLY

In [10]:
df = db_sync.db.fetch_data('payment')
df = df[df.miner == miner]
dates = df.lastpayment.unique()

ls = []
for date in dates:
    temp = df[df.lastpayment == date]
    temp = temp[temp.created_at == max(temp.created_at)]
    ls.append(temp)

new_df = pd.concat(ls)
new_df

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:180: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

,pendingshares,pendingbalance,totalpaid,todaypaid,schema,price,lastpayment,lastpaymentlink,created_at,miner
1255,98.33,0.00,338.45,1.464749,PPLNS,1.18,2024-05-08,https://explorer.ergoplatform.com/en/transacti...,2024-05-08 11:56:01.671197,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
14059,190.96,0.00,343.88,0.000000,PPLNS,1.30,2024-05-09,https://explorer.ergoplatform.com/en/transacti...,2024-05-09 22:42:01.648600,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
309643,110.86,18.51,381.87,0.000000,PPLNS,1.26,2024-05-1,https://explorer.ergoplatform.com/en/transacti...,2024-05-19 13:22:01.507435,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
31255,123.67,0.00,347.87,3.990570,PPLNS,1.31,2024-05-10,https://explorer.ergoplatform.com/en/transacti...,2024-05-10 09:20:02.261625,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
45263,238.67,0.00,356.06,0.000000,PPLNS,1.27,2024-05-11,https://explorer.ergoplatform.com/en/transacti...,2024-05-12 00:32:01.544833,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
58824,73.43,0.00,358.86,2.800531,PPLNS,1.27,2024-05-12,https://explorer.ergoplatform.com/en/transacti...,2024-05-12 09:30:02.352770,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
162804,229.85,18.60,361.77,0.000000,PPLNS,1.29,2024-05-13,https://explorer.ergoplatform.com/en/transacti...,2024-05-15 21:52:01.491294,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
344334,109.48,4.71,401.96,0.000000,PPLNS,1.26,2024-05-19,https://explorer.ergoplatform.com/en/transacti...,2024-05-20 10:10:02.368230,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...

In [11]:
db_sync.db.get_db_size()

'152 MB'

In [12]:
df = db_sync.db.fetch_data('live_worker')
df = df[df.created == max(df.created)]
df = df[df.worker == 'totals']
df

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:180: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

,worker,hashrate,shares_per_second,created,miner,effort,ttf,last_block_found
147016,totals,3475.0,0.33,2024-05-20 16:08:34,9gXo8m2VyHvQ3FGvCg1GNWfyM5uX27BEKNCXDjQ6GiFsMJ...,383.56,4.47,2024-05-03 12:13:18
147019,totals,1906.0,0.22,2024-05-20 16:08:34,9eZVqXVnrVWQKK19b7E7kp4ZyNqanp2z1mpKUJRaouNsme...,122.23,8.16,2024-05-10 16:49:32
147024,totals,2291.0,0.14,2024-05-20 16:08:34,9hwEKqgW4XjRi7uYjRcsZHiRiuNT3dMHsR3J75BNSrGDQy...,3.35,6.79,2024-05-20 10:42:33
147026,totals,2085.0,0.14,2024-05-20 16:08:34,9fRQ8iCiCZekAewtjHmu7AmucWjvBTNUMeBFtnNkpfyWsN...,87.75,7.46,2024-05-14 03:05:05
147029,totals,1440.0,0.08,2024-05-20 16:08:34,9eoPRhRmJQ71TPSkk2eUmMXYpxUVvZvFQo5uB9qjPBM4e3...,88.77,10.80,2024-05-11 02:05:22
147032,totals,2273.0,0.14,2024-05-20 16:08:34,9hSk13XDU8keWAp3KxKSgUVCkfDcw577jAjM6SgbRpuYeL...,329.51,6.84,2024-04-28 03:06:52
147034,totals,1590.0,0.07,2024-05-20 16:08:34,9fy4KkHt9Xavq9R7Wq16euW4JjH1mYwBtV7SNNtAtwnQ6q...,0.00,9.78,N/A
147037,totals,1444.0,0.19,2024-05-20 16:08:34,9gLMeVQbDWX522WUzBwmVnr2Avqki7wdz7c9MpcpkgVJE5...,55.67,10.77,2024-05-14 16:16:28
147039,totals,834.0,0.08,2024-05-20 16:08:34,9ggrhWJVjTHHUrK8qJThWi1yBscmETnT3nxTwVDfQQPCAS...,0.00,18.65,N/A
147042,totals,1580.0,0.12,2024-05-20 16:08:34,9f26fcLvpCkcJyY9SLXMMRZ2k3GeKxb8bERTE7cVp1SC3X...,94.12,9.84,2024-05-11 09:50:29
147044,totals,1327.0,0.07,2024-05-20 16:08:34,9hxPoaiJfm4yTisDX1ctC4Kd7PANdNE2EiJa5EhLMJk4BQ...,9.40,11.72,2024-05-19 13:43:03
147046,totals,709.0,0.07,2024-05-20 16:08:34,9eYN6LACnheBuPYPMjhoERN5gjw2NE7mTfri378gZPazco...,0.00,21.93,N/A
147049,totals,1159.0,0.16,2024-05-20 16:08:34,9fRBLHy5GMofGGNyFkYJypZbwL8VKQwiVinEJ4NRfUgMuJ...,6.61,13.42,2024-05-19 18:52:41
147051,totals,1070.0,0.08,2024-05-20 16:08:34,9gwk97nY8Uc6kLcSYs4ueWttY5EKyfsrbiyVQWFdUaWvd4...,231.40,14.53,2024-04-17 01:03:11
147053,totals,994.0,0.06,2024-05-20 16:08:34,9fjQi1JrgFZ9QBKGbE7EYDwUwAvGUk95Wa92kV2D4EnggN...,34.61,15.64,2024-05-15 06:12:21
147055,totals,707.0,0.08,2024-05-20 16:08:34,9fxwXaXp7x3i8gzfZ5zqMJJK1DbtyUeVGQL3mBaCg2cB8y...,99.81,22.00,2024-04-28 17:16:48
147059,totals,746.0,0.07,2024-05-20 16:08:34,9exkqG2KBpdeHKby84pSehSZt9sKQitAqjuguHXdd25eEJ...,34.12,20.85,2024-05-13 13:28:18
147062,totals,611.0,0.09,2024-05-20 16:08:34,9gW4BxS6x8pF7BVMsE2VPpKTEHaDB9Nw1mp6MEpn5MWAmX...,0.00,25.45,N/A
147064,totals,161.0,0.04,2024-05-20 16:08:34,9h4Q7d8b98Pr77CVd99n5gcWi6tz4MtkyGRFFkh2FQDYfW...,0.00,96.59,N/A
147066,totals,674.0,0.07,2024-05-20 16:08:34,9hDaPXB2Tx5BHQfiqcELp6m3wskR4g8sa5Tna4G9y4TeMa...,4.24,23.07,2024-05-19 16:41:31
147068,totals,192.0,0.04,2024-05-20 16:08:34,9f5vwtxyRP87wmc8ezyKbL7ryaNhDrgWUVBEZpQKnw16SW...,34.47,80.99,2024-04-22 18:11:34
147070,totals,485.0,0.07,2024-05-20 16:08:34,9gE6BVPJ8fxoUUkvETvNcqyJn9b561QyiwJsppDUs77sEF...,0.00,32.06,N/A
147073,totals,498.0,0.11,2024-05-20 16:08:34,9ggYKoC58jQkbGNhCKqcLMsuK3qCE5ieqTPx28KrY5jJ5S...,86.98,31.23,2024-04-23 12:18:50
147075,totals,326.0,0.06,2024-05-20 16:08:34,9g4f585vPtgA5PKhSRcaPBhtfW3HYRw2qe3aemxxnD5Y1K...,50.12,47.70,2024-04-26 18:24:58
147078,totals,429.0,0.09,2024-05-20 16:08:34,9g7fAbNvKsTUoQHx6CunQ3LhUmFuXwU8vZSU7qKMe94v9U...,0.00,36.25,N/A
147082,totals,383.0,0.09,2024-05-20 16:08:34,9gqJXY1t7mUn7rurrcbdY1td226N1TwzDHRZ1xXeUiUERZ...,0.00,40.60,N/A
147084,totals,2070.0,0.19,2024-05-20 16:08:34,9hUWH7MTuDSPxSQiQuUecLf6SnCCN8ydt8XigBD3TN42zd...,26.77,7.51,2024-05-18 15:53:57
147085,totals,82.0,0.02,2024-05-20 16:08:34,9gWtU5oRt4yuNU4WELRAHm49CCpwtRoVRkjs1DQkoKZmEu...,0.00,189.65,N/A
147086,totals,331.0,0.06,2024-05-20 16:08:34,9hYeUWUG2dAM6sZb9vr5qgF1gACEGQPLN9cbXjxERmJS89...,0.00,46.98,N/A
147088,totals,250.0,0.05,2024-05-20 16:08:34,9eiBDqvLs2Z5PobwMmHtZsczn7a4yy73mYsKghkqgCZ5Nf...,0.00,62.20,N/A
147090,totals,280.0,0.06,2024-05-20 16:08:34,9eZPTmn8zp5GJ7KZwTo8cEuxNdezWaY3hBbLeWid7EAZed...,77.14,55.54,2024-04-07 19:55:43
147092,totals,141.0,0.03,2024-05-20 16:08:34,9gLRSzqiMGdMU39jG6hMAnwHT748HiTrY6wz1jjFGkJYaM...,0.00,110.29,N/A
147094,totals,238.0,0.05,2024-05-20 16:08:34,9feNRbYuVz2nQy1V8t2z5saYnWKwmGJ2nYgcMdXBjqYXqH...,0.00,65.34,N/A
147096,totals,261.0,0.05,2024-05-20 16:08:34,9f1gJS9FhVsBZPZZ4goGsKKqj5EzniSVYpH9WcEi1jxa2Y...,0.00,59.58,N/A
147098,totals,199.0,0.04,2024-05-20 16:08:34,9iGCyowxwgf6cQef1RfEw6UCYoHJi6q1hZvKvcWyFY1kuL...,0.00,78.14,N/A
147100,totals,100.0,0.02,2024-05-20 16:08:34,9fs1QU7tsDvYNo1aVmMManemdF5Ud2QLavCTFABP3Smm3H...,0.00,155.51,N/A
147104,totals,69.0,0.01,2024-05-20 16:08:34,9g5jXf74UWyXEJ4BZJ8gVp2ZJzG9bgPVijCtuUrWvv5DWH...,0.00,225.38,N/A
147106,totals,115.0,0.03,2024-05-20 16:08:34,9frM6fZpsttkBJYHsYzsiYDXdCjCkeVY4NUXzMqabmYw8x...,0.00,135.22,N/A
147108,totals,88.0,0.02,2024-05-20 16:08:34,9fq3byFPSNBZogH7R4k8cLmeFiYghS6whfdMWcumctaAsr...,0.00,176.71,N/A
147110,totals,97.0,0.02,2024-05-20 16:08:34,9feFmoH5ftSpUVZXL9NATBjw5G3JHcBqbA3vEEcE7auHBv...,0.00,160.32,N/A
147113,totals,84.0,0.02,2024-05-20 16:08:34,9gyKCPYkaBJp7z8NxxCygjwB6u9GLudiakUEUPpZ1bjhbJ...,0.00,185.13,N/A
147134,totals,22139.0,1.34,2024-05-20 16:08:34,9gNEKbpPSNfgWkhxsMF4Z9L7uNiXFfsEX4XTVF5XK4kwpQ...,338.27,0.70,2024-05-18 07:08:31
147137,totals,3837.0,0.11,2024-05-20 16:08:34,9gHULKUh8kLBBc6F6ddtyzeyhzz2KzGerPbFw7ZHmSUPrR...,249.40,4.05,2024-05-10 13:35:01
147142,totals,5211.0,0.21,2024-05-20 16:08:34,9f3FRr4XudxVs1V35At1X5yj7LmQmnWqG46LqFKVNRf2Tu...,14.17,2.98,2024-05-20 06:01:15
147147,totals,5145.0,0.28,2024-05-20 16:08:34,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...,108.24,3.02,2024-05-17 09:38:58
147151,totals,3352.0,0.18,2024-05-20 16:08:34,9i3P4Ah9jp7nnSNMg6gxjXXHEWjkkBbPJR5RLRkMwEt3DZ...,50.11,4.64,2024-05-18 08:22:12
147157,totals,4141.0,0.36,2024-05-20 16:08:34,9h6bjuzth7XDNeBxwFjpYSfmUkfBiepE8MGJcvmsVkeCtG...,89.30,3.75,2024-05-17 07:41:18
147159,totals,2818.0,0.14,2024-05-20 16:08:34,9fHLdYBz5fPdDfMkGMfAsuj6EfXCpmM4GkamT23xeT3hzd...,188.50,5.52,2024-05-10 06:30:40
147161,totals,891.0,0.14,2024-05-20 16:08:34,9g7vDJUyWWDYkh6me5zZPyfoLdTweVfEdX2JbVnmZc3yEA...,6.70,17.45,2024-05-19 12:05:57
147162,totals,322.0,0.07,2024-05-20 16:08:34,9gumpDg6SLtZXDHFuijHnKQJ473B5bjcs5BVkyENDgRpD1...,0.00,48.30,N/A
147164,totals,129.0,0.03,2024-05-20 16:08:34,9haAysnicciRTb8Qexr3Qogrv1HwDk7AUKvoQkeSFnNMj3...,0.00,120.55,N/A

In [13]:
df = db_sync.db.fetch_data('payment')
df = df[df.miner == miner]
dates = df.lastpayment.unique() # get all of the payment dates
ls = []
for date in dates:
    temp = df[df.lastpayment == date]
    temp = temp[temp.created_at == max(temp.created_at)] # filter by the latest payment stamp
    ls.append(temp)

df = pd.concat(ls)
df

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:180: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

,pendingshares,pendingbalance,totalpaid,todaypaid,schema,price,lastpayment,lastpaymentlink,created_at,miner
1255,98.33,0.00,338.45,1.464749,PPLNS,1.18,2024-05-08,https://explorer.ergoplatform.com/en/transacti...,2024-05-08 11:56:01.671197,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
14059,190.96,0.00,343.88,0.000000,PPLNS,1.30,2024-05-09,https://explorer.ergoplatform.com/en/transacti...,2024-05-09 22:42:01.648600,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
309643,110.86,18.51,381.87,0.000000,PPLNS,1.26,2024-05-1,https://explorer.ergoplatform.com/en/transacti...,2024-05-19 13:22:01.507435,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
31255,123.67,0.00,347.87,3.990570,PPLNS,1.31,2024-05-10,https://explorer.ergoplatform.com/en/transacti...,2024-05-10 09:20:02.261625,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
45263,238.67,0.00,356.06,0.000000,PPLNS,1.27,2024-05-11,https://explorer.ergoplatform.com/en/transacti...,2024-05-12 00:32:01.544833,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
58824,73.43,0.00,358.86,2.800531,PPLNS,1.27,2024-05-12,https://explorer.ergoplatform.com/en/transacti...,2024-05-12 09:30:02.352770,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
162804,229.85,18.60,361.77,0.000000,PPLNS,1.29,2024-05-13,https://explorer.ergoplatform.com/en/transacti...,2024-05-15 21:52:01.491294,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
344334,109.48,4.71,401.96,0.000000,PPLNS,1.26,2024-05-19,https://explorer.ergoplatform.com/en/transacti...,2024-05-20 10:10:02.368230,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...

In [14]:
dates = [date for date in df['lastpayment'] if len(date) > 9]
df[df['lastpayment'].isin(dates)]

,pendingshares,pendingbalance,totalpaid,todaypaid,schema,price,lastpayment,lastpaymentlink,created_at,miner
1255,98.33,0.00,338.45,1.464749,PPLNS,1.18,2024-05-08,https://explorer.ergoplatform.com/en/transacti...,2024-05-08 11:56:01.671197,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
14059,190.96,0.00,343.88,0.000000,PPLNS,1.30,2024-05-09,https://explorer.ergoplatform.com/en/transacti...,2024-05-09 22:42:01.648600,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
31255,123.67,0.00,347.87,3.990570,PPLNS,1.31,2024-05-10,https://explorer.ergoplatform.com/en/transacti...,2024-05-10 09:20:02.261625,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
45263,238.67,0.00,356.06,0.000000,PPLNS,1.27,2024-05-11,https://explorer.ergoplatform.com/en/transacti...,2024-05-12 00:32:01.544833,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
58824,73.43,0.00,358.86,2.800531,PPLNS,1.27,2024-05-12,https://explorer.ergoplatform.com/en/transacti...,2024-05-12 09:30:02.352770,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
162804,229.85,18.60,361.77,0.000000,PPLNS,1.29,2024-05-13,https://explorer.ergoplatform.com/en/transacti...,2024-05-15 21:52:01.491294,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
344334,109.48,4.71,401.96,0.000000,PPLNS,1.26,2024-05-19,https://explorer.ergoplatform.com/en/transacti...,2024-05-20 10:10:02.368230,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...

In [15]:
df

,pendingshares,pendingbalance,totalpaid,todaypaid,schema,price,lastpayment,lastpaymentlink,created_at,miner
1255,98.33,0.00,338.45,1.464749,PPLNS,1.18,2024-05-08,https://explorer.ergoplatform.com/en/transacti...,2024-05-08 11:56:01.671197,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
14059,190.96,0.00,343.88,0.000000,PPLNS,1.30,2024-05-09,https://explorer.ergoplatform.com/en/transacti...,2024-05-09 22:42:01.648600,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
309643,110.86,18.51,381.87,0.000000,PPLNS,1.26,2024-05-1,https://explorer.ergoplatform.com/en/transacti...,2024-05-19 13:22:01.507435,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
31255,123.67,0.00,347.87,3.990570,PPLNS,1.31,2024-05-10,https://explorer.ergoplatform.com/en/transacti...,2024-05-10 09:20:02.261625,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
45263,238.67,0.00,356.06,0.000000,PPLNS,1.27,2024-05-11,https://explorer.ergoplatform.com/en/transacti...,2024-05-12 00:32:01.544833,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
58824,73.43,0.00,358.86,2.800531,PPLNS,1.27,2024-05-12,https://explorer.ergoplatform.com/en/transacti...,2024-05-12 09:30:02.352770,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
162804,229.85,18.60,361.77,0.000000,PPLNS,1.29,2024-05-13,https://explorer.ergoplatform.com/en/transacti...,2024-05-15 21:52:01.491294,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
344334,109.48,4.71,401.96,0.000000,PPLNS,1.26,2024-05-19,https://explorer.ergoplatform.com/en/transacti...,2024-05-20 10:10:02.368230,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...

In [16]:
url = '{}/{}/{}'.format(db_sync.base_api, 'miners', miner)
mining_data = db_sync.get_api_data(url)        
payment_data = {k: v for k, v in mining_data.items() if k not in ['performance', 'performanceSamples']}
payment_data['lastPayment'] = mining_data['lastPayment'] #[:-16]
payment_data

{'pendingShares': 109.69432900627552,
 'pendingBalance': 4.712266769013,
 'totalPaid': 401.962181429429,
 'todayPaid': 0,
 'lastPayment': '2024-05-19T19:23:20.593302Z',
 'lastPaymentLink': 'https://explorer.ergoplatform.com/en/transactions/c2211de6678af5794c5be2591aa64fa927e72398c68e65c9bd1dd5fb09765b80'}

In [17]:
payment_data

{'pendingShares': 109.69432900627552,
 'pendingBalance': 4.712266769013,
 'totalPaid': 401.962181429429,
 'todayPaid': 0,
 'lastPayment': '2024-05-19T19:23:20.593302Z',
 'lastPaymentLink': 'https://explorer.ergoplatform.com/en/transactions/c2211de6678af5794c5be2591aa64fa927e72398c68e65c9bd1dd5fb09765b80'}

In [18]:
df = db_sync.db.fetch_data('block')
bf = df[df.time_found == max(df.time_found)]
bf.confirmationprogress.item()

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:180: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

100

In [20]:
df = db_sync.db.fetch_data('block')
df

,poolid,blockheight,networkdifficulty,status,confirmationprogress,effort,transactionconfirmationdata,reward,infolink,hash,miner,source,time_found
0,ErgoSigmanauts,1261083,352459.70,confirmed,100,1.81,54bfa452ce8edae4,27.00,https://explorer.ergoplatform.com/en/blocks/a9...,a9fc7bd19aa8d8e2e3a8e2280438dddeb20516167a9bee...,9f3...YsAik,ErgoSigmanauts,2024-05-10 02:15:36
1,ErgoSigmanauts,1258231,415604.76,confirmed,100,0.43,57d1a1b77952d5be,27.00,https://explorer.ergoplatform.com/en/blocks/a7...,a757e9f5881ac9a21e8c33b004a61dd6e5de753154fd75...,9hU...dSGtj,ErgoSigmanauts,2024-05-06 01:55:23
2,ErgoSigmanauts,1254265,386513.23,confirmed,100,3.16,501090b5ff36737c,27.02,https://explorer.ergoplatform.com/en/blocks/0e...,0e48a40b9cdffafc5448cf5c0255a5baa96cd88292bf2a...,9h6...YYYAb,ErgoSigmanauts,2024-04-30 12:52:07
3,ErgoSigmanauts,1259401,338744.91,confirmed,100,0.77,5d11000a4864bcd4,27.02,https://explorer.ergoplatform.com/en/blocks/86...,869dc103e6032cfba5f2d1cbbc0df70f37f95266b084a4...,9gL...DUhcN,ErgoSigmanauts,2024-05-07 17:45:32
4,ErgoSigmanauts,1256952,387536.20,confirmed,100,1.04,50633b970a2e278d,27.00,https://explorer.ergoplatform.com/en/blocks/05...,05ae6a6369d021d135773cdc1eccbe27b9b8da13d13598...,9fL...prSrh,ErgoSigmanauts,2024-05-04 06:46:01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,ErgoSigmanauts,1267808,336275.93,confirmed,100,3.99,5abd00272c4afb70,27.02,https://explorer.ergoplatform.com/en/blocks/d8...,d81ab5cd625debe6e611f00426ceffcd2df39fa4ce64a7...,9g7...9uUJN,ErgoSigmanauts,2024-05-19 12:05:57
127,ErgoSigmanauts,1257115,356774.63,confirmed,100,0.23,50f3b0411ea563ab,27.05,https://explorer.ergoplatform.com/en/blocks/b9...,b9aa406bd07b9df9c97c853bfeb7cd5a2fbdf17db2dd37...,9f3...YsAik,ErgoSigmanauts,2024-05-04 12:27:57
128,ErgoSigmanauts,1244611,350337.67,confirmed,100,0.30,13309b8b1531ac3d,27.00,https://explorer.ergoplatform.com/en/blocks/4a...,4ac405b82c909606840b4abb83acd42e79aa74ac9dfcfa...,9gw...Xhqys,ErgoSigmanauts,2024-04-17 01:03:11
129,ErgoSigmanauts,1266547,264041.03,confirmed,100,1.95,5a81000adce74168,27.00,https://explorer.ergoplatform.com/en/blocks/a8...,a8192d00ed093ae8eb0efc74a40329814841dd127cb6aa...,9hU...dSGtj,ErgoSigmanauts,2024-05-17 18:09:50
130,ErgoSigmanauts,1247634,390680.08,confirmed,100,3.04,1a1329402f2206ed,27.07,https://explorer.ergoplatform.com/en/blocks/c7...,c7b7ef3a8c7af63a7729de240de056beff246f9d99aebd...,9eh...ApYkk,ErgoSigmanauts,2024-04-21 05:49:18

In [21]:
db_sync = DataSyncer(config_path="../conf")
url = '{}/{}'.format(db_sync.base_api, 'blocks?pageSize=5000')
mining_data = db_sync.get_api_data(url)

In [23]:
mining_data[0].keys()

dict_keys(['poolId', 'blockHeight', 'networkDifficulty', 'status', 'confirmationProgress', 'effort', 'transactionConfirmationData', 'reward', 'infoLink', 'hash', 'miner', 'source', 'created'])

In [2]:
columns = ['poolId', 'blockHeight', 'networkDifficulty', 'status', 'confirmationProgress', 'effort',
               'transactionConfirmationData', 'reward', 'infoLink', 'hash', 'miner', 'source', 'created']
db_sync = DataSyncer(config_path="../conf", db_name='localhost')

url = '{}/{}'.format(db_sync.base_api, 'blocks?pageSize=5000')
block_data = db_sync.get_api_data(url)   

block_df = pd.DataFrame(block_data, columns=columns)
block_df

,poolId,blockHeight,networkDifficulty,status,confirmationProgress,effort,transactionConfirmationData,reward,infoLink,hash,miner,source,created
0,ErgoSigmanauts,1268462,310719.301046,confirmed,1,0.770851,5061cf937587c7c6,27.004300,https://explorer.ergoplatform.com/en/blocks/91...,91c15c11d50be769e606779a9373eef192abb5664ca79f...,9hwEKqgW4XjRi7uYjRcsZHiRiuNT3dMHsR3J75BNSrGDQy...,ErgoSigmanauts,2024-05-20T10:42:33.652214Z
1,ErgoSigmanauts,1268326,320375.154087,confirmed,1,2.074200,5c1ac1c3c7c770ce,27.003000,https://explorer.ergoplatform.com/en/blocks/8b...,8b6cb64b628a519aff30ea498650c09e800ddeef1ec987...,9f3FRr4XudxVs1V35At1X5yj7LmQmnWqG46LqFKVNRf2Tu...,ErgoSigmanauts,2024-05-20T06:01:15.904865Z
2,ErgoSigmanauts,1267991,308134.350726,confirmed,1,0.421351,55bf8e2c557b0863,27.003253,https://explorer.ergoplatform.com/en/blocks/2e...,2e3c3dd10fa250fa35459d6d45c720aef1fdf6082ed936...,9fRBLHy5GMofGGNyFkYJypZbwL8VKQwiVinEJ4NRfUgMuJ...,ErgoSigmanauts,2024-05-19T18:52:41.180515Z
3,ErgoSigmanauts,1267934,317121.238241,confirmed,1,0.529463,56405e5352747dd4,27.085400,https://explorer.ergoplatform.com/en/blocks/50...,50c138c9e7dd4d9abc9f6869064dbdd337c3ba7bb0e3d6...,9hDaPXB2Tx5BHQfiqcELp6m3wskR4g8sa5Tna4G9y4TeMa...,ErgoSigmanauts,2024-05-19T16:41:31.192756Z
4,ErgoSigmanauts,1267854,317121.238241,confirmed,1,0.286497,5bdcdfadd0a0a181,27.001000,https://explorer.ergoplatform.com/en/blocks/97...,97ec01d0cc4a0e19e4e36cf76420f6eb0177421f72892e...,9hxPoaiJfm4yTisDX1ctC4Kd7PANdNE2EiJa5EhLMJk4BQ...,ErgoSigmanauts,2024-05-19T13:43:03.506763Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,ErgoSigmanauts,1230749,360986.500966,confirmed,1,0.287231,d8a48cee009b608c,30.006550,https://explorer.ergoplatform.com/en/blocks/2e...,2e2b04e088834393eafa5aac17d0fc641f4a188d6dc873...,9gwk97nY8Uc6kLcSYs4ueWttY5EKyfsrbiyVQWFdUaWvd4...,ErgoSigmanauts,2024-03-28T15:40:37.400137Z
127,ErgoSigmanauts,1230547,434381.378191,confirmed,1,0.797385,d6c1191549ab2f07,30.027600,https://explorer.ergoplatform.com/en/blocks/c5...,c5886b3606b842b4a0ecaeda2d6270ac3238e7e0da37d2...,9fYvQMsMN3NNaw33cAFnRdyHy1DpxtxfADvGqUV3ocLptw...,ErgoSigmanauts,2024-03-28T08:26:49.370775Z
128,ErgoSigmanauts,1230104,347635.796935,confirmed,1,4.752955,d153e8105c7c0b57,30.001000,https://explorer.ergoplatform.com/en/blocks/b0...,b03937a8404d47fed3d7050a93a6e6b940100e4c008a66...,9fYvQMsMN3NNaw33cAFnRdyHy1DpxtxfADvGqUV3ocLptw...,ErgoSigmanauts,2024-03-27T18:07:25.358611Z
129,ErgoSigmanauts,1223980,416310.690227,confirmed,1,0.895507,300b000932aead3a,30.007862,https://explorer.ergoplatform.com/en/blocks/83...,83c740633d4aa9e61775dcab0d2ef20dd4d11c275424fa...,9i8wsL9HYe4wRtuxXtnvki31uGJd6avKoQ79BXbz2sHWNZ...,ErgoSigmanauts,2024-03-19T04:19:20.685251Z
130,ErgoSigmanauts,1221911,421209.622611,confirmed,1,2.867494,705c89a6a4e552cf,30.007100,https://explorer.ergoplatform.com/en/blocks/47...,47dd2792f0fd255fc8fc4b0a12903b351245fb7083ea5e...,9iQS22vfWdF2N84Lvv9jgAMFGLyL7t17SWbHGEfaddaG7Z...,ErgoSigmanauts,2024-03-16T06:45:27.859919Z