In [1]:
from utils.api_2_db import DataSyncer
import pandas as pd
from utils.update_blocks_and_workers import update_blocks_and_live_workers
from utils.update_payment_and_performance import update_payment_and_performance
from utils.update_pool_stats import update_pool_stats
from utils.init_db import init_db

In [2]:
init_db()

intializing DB
Connecting to DB instance
connected
tables created
UPDATED STATS TABLE SUCCESFULLY

TypeError: type str doesn't define __round__ method

In [4]:
db_sync = DataSyncer(config_path="../conf")
miner = '9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPVApYkk'
# db_sync.db.create_database('sigma-mining-db')

Connecting to DB instance
connected

In [5]:
def get_size_and_tables():
    print(db_sync.db.get_db_size())
    df = db_sync.db.fetch_data('payment')
    print(len(df), 'PAYMENT')
    
    df = db_sync.db.fetch_data('live_worker')
    print(len(df), 'LIVE')
    
    df = db_sync.db.fetch_data('stats')
    print(len(df), 'STATS',)
    
    df = db_sync.db.fetch_data('block')
    print(len(df), 'BLOCKS')

In [6]:
get_size_and_tables()

10 MB
163 PAYMENT
524 LIVE
26 STATS
164 BLOCKS

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:265: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

In [13]:
db_sync.db.fetch_data('stats')

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:265: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

,fee,paid,blocks,last_block_found,enabled,minimumpayment,payoutscheme,connectedminers,poolhashrate,sharespersecond,...,networkhashrate,networkdifficulty,lastnetworkblocktime,blockheight,connectedpeers,rewardtype,pooleffort,poolttf,price,insert_time_stamp
0,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,52,94.50,7.0,...,10.502913,1.260350,2024-05-28 20:47:51.800749,1274490,121,POW,34.27,0.15,1.21,2024-05-28 14:48:02.915155
1,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,52,94.50,7.0,...,10.502913,1.260350,2024-05-28 20:47:51.800749,1274490,121,POW,34.47,0.15,1.21,2024-05-28 14:48:29.715794
2,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,92.59,7.0,...,10.502913,1.260350,2024-05-28 20:52:30.369552,1274492,122,POW,35.71,0.16,1.21,2024-05-28 14:52:53.065882
3,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,92.59,7.0,...,10.502913,1.260350,2024-05-28 20:52:30.369552,1274492,122,POW,35.71,0.16,1.21,2024-05-28 14:52:53.018904
4,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,92.59,7.0,...,10.502913,1.260350,2024-05-28 20:52:30.369552,1274492,122,POW,35.71,0.16,1.21,2024-05-28 14:52:53.295036
5,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,92.59,7.0,...,10.502913,1.260350,2024-05-28 20:52:30.369552,1274492,122,POW,35.71,0.16,1.21,2024-05-28 14:52:53.435180
6,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,92.59,7.0,...,10.502913,1.260350,2024-05-28 20:52:30.369552,1274492,122,POW,35.71,0.16,1.21,2024-05-28 14:52:53.156668
7,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,92.59,7.0,...,10.502913,1.260350,2024-05-28 20:52:30.369552,1274492,122,POW,35.71,0.16,1.21,2024-05-28 14:52:53.250550
8,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,92.59,7.0,...,10.502913,1.260350,2024-05-28 20:52:30.369552,1274492,122,POW,35.71,0.16,1.21,2024-05-28 14:52:53.110661
9,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,92.59,7.0,...,10.502913,1.260350,2024-05-28 20:52:30.369552,1274492,122,POW,35.71,0.16,1.21,2024-05-28 14:52:53.202829
10,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.37,6.0,...,10.502913,1.260350,2024-05-28 20:54:59.490893,1274496,122,POW,36.09,0.16,1.21,2024-05-28 14:55:45.286200
11,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.37,6.0,...,10.502913,1.260350,2024-05-28 20:54:59.490893,1274496,122,POW,36.09,0.16,1.21,2024-05-28 14:55:45.405460
12,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.37,6.0,...,10.502913,1.260350,2024-05-28 20:54:59.490893,1274496,122,POW,36.09,0.16,1.21,2024-05-28 14:55:45.614684
13,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.37,6.0,...,10.502913,1.260350,2024-05-28 20:54:59.490893,1274496,122,POW,36.09,0.16,1.21,2024-05-28 14:55:45.457804
14,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.84,7.0,...,10.502913,1.260350,2024-05-28 20:54:59.490893,1274496,122,POW,36.82,0.16,1.21,2024-05-28 14:57:01.108755
15,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.84,7.0,...,10.502913,1.260350,2024-05-28 20:54:59.490893,1274496,122,POW,36.82,0.16,1.21,2024-05-28 14:57:01.341402
16,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.84,7.0,...,10.502913,1.260350,2024-05-28 20:54:59.490893,1274496,122,POW,36.82,0.16,1.21,2024-05-28 14:57:01.229164
17,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.84,7.0,...,10.502913,1.260350,2024-05-28 20:54:59.490893,1274496,122,POW,36.83,0.16,1.21,2024-05-28 14:57:01.398995
18,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.84,7.0,...,10.502913,1.260350,2024-05-28 20:54:59.490893,1274496,122,POW,36.83,0.16,1.21,2024-05-28 14:57:01.285301
19,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.84,7.0,...,10.502913,1.260350,2024-05-28 20:54:59.490893,1274496,122,POW,36.82,0.16,1.21,2024-05-28 14:57:00.995484
20,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.84,7.0,...,10.047646,1.205718,2024-05-28 20:58:37.969834,1274498,120,POW,39.22,0.15,1.21,2024-05-28 14:58:37.857286
21,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.84,7.0,...,10.047646,1.205718,2024-05-28 20:58:37.969834,1274498,120,POW,39.23,0.15,1.21,2024-05-28 14:58:39.046705
22,0.9,4321.094287,164,2024-05-28 19:31:53,True,0.5,PPLNS,53,90.84,7.0,...,10.047646,1.205718,2024-05-28 20:58:37.969834,1274498,120,POW,39.24,0.15,1.21,2024-05-28 14:58:40.061281

In [7]:
db_sync.db.create_table('block', db_sync.block_headers)

True

In [7]:
db_sync.db.create_table('payment', db_sync.payment_headers)
db_sync.db.fetch_data('payment')

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:265: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

,pendingshares,pendingbalance,totalpaid,todaypaid,schema,price,lastpayment,lastpaymentlink,participation,created_at,miner
0,2103.52,0.00,812.40,0.0,PPLNS,1.21,2024-05-,https://explorer.ergoplatform.com/en/transacti...,None,2024-05-28 14:48:02.915155,9gNEKbpPSNfgWkhxsMF4Z9L7uNiXFfsEX4XTVF5XK4kwpQ...
1,437.62,0.00,41.07,0.0,PPLNS,1.21,2024-05-27,https://explorer.ergoplatform.com/en/transacti...,None,2024-05-28 14:48:02.915155,9fLytFFzTYALknc2AZ2dRKeg8sLZwe4LX5qAB3FwDysMEe...
2,345.63,0.00,277.99,0.0,PPLNS,1.21,2024-05-27,https://explorer.ergoplatform.com/en/transacti...,None,2024-05-28 14:48:02.915155,9f3FRr4XudxVs1V35At1X5yj7LmQmnWqG46LqFKVNRf2Tu...
3,40.21,0.00,43.65,0.0,PPLNS,1.21,2024-05-27,https://explorer.ergoplatform.com/en/transacti...,None,2024-05-28 14:48:02.915155,9eZVqXVnrVWQKK19b7E7kp4ZyNqanp2z1mpKUJRaouNsme...
4,305.79,6.44,443.33,0.0,PPLNS,1.21,2024-05-26,https://explorer.ergoplatform.com/en/transacti...,None,2024-05-28 14:48:02.915155,9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPV...
...,...,...,...,...,...,...,...,...,...,...,...
158,7.18,0.33,1.73,0.0,PPLNS,1.21,2024-05-25,https://explorer.ergoplatform.com/en/transacti...,None,2024-05-28 14:58:37.857286,9fvDaBsLKmzP67Cp2i2bmhM1359HhJCrej8y5EGoUcmXDr...
159,5.27,0.45,3.60,0.0,PPLNS,1.21,2024-05-25,https://explorer.ergoplatform.com/en/transacti...,None,2024-05-28 14:58:37.857286,9gWtU5oRt4yuNU4WELRAHm49CCpwtRoVRkjs1DQkoKZmEu...
160,5.42,0.38,1.03,0.0,PPLNS,1.21,2024-05-24,https://explorer.ergoplatform.com/en/transacti...,None,2024-05-28 14:58:37.857286,9g5jXf74UWyXEJ4BZJ8gVp2ZJzG9bgPVijCtuUrWvv5DWH...
161,3.81,0.48,1.02,0.0,PPLNS,1.21,2024-05-19,https://explorer.ergoplatform.com/en/transacti...,None,2024-05-28 14:58:37.857286,9gyKCPYkaBJp7z8NxxCygjwB6u9GLudiakUEUPpZ1bjhbJ...
162,5.42,0.30,1.05,0.0,PPLNS,1.21,2024-05-24,https://explorer.ergoplatform.com/en/transacti...,None,2024-05-28 14:58:37.857286,9haAysnicciRTb8Qexr3Qogrv1HwDk7AUKvoQkeSFnNMj3...

In [12]:
db_sync.db.create_table('live_worker', db_sync.live_worker_headers)
db_sync.db.fetch_data('live_worker')

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:265: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

,worker,hashrate,shares_per_second,created,miner,effort,ttf,last_block_found
0,d_tim_4_v,1368.0,0.07,2024-05-28 20:56:48,9gNEKbpPSNfgWkhxsMF4Z9L7uNiXFfsEX4XTVF5XK4kwpQ...,16.45,10.20,2024-05-27 04:42:19
1,e_tim_5_v,918.0,0.07,2024-05-28 20:56:48,9gNEKbpPSNfgWkhxsMF4Z9L7uNiXFfsEX4XTVF5XK4kwpQ...,11.04,15.20,2024-05-27 04:42:19
2,f_tim_6_v,954.0,0.07,2024-05-28 20:56:48,9gNEKbpPSNfgWkhxsMF4Z9L7uNiXFfsEX4XTVF5XK4kwpQ...,11.47,14.63,2024-05-27 04:42:19
3,h_tim_8,1582.0,0.08,2024-05-28 20:56:48,9gNEKbpPSNfgWkhxsMF4Z9L7uNiXFfsEX4XTVF5XK4kwpQ...,19.02,8.82,2024-05-27 04:42:19
4,j_tim_10,630.0,0.05,2024-05-28 20:56:48,9gNEKbpPSNfgWkhxsMF4Z9L7uNiXFfsEX4XTVF5XK4kwpQ...,7.58,22.15,2024-05-27 04:42:19
...,...,...,...,...,...,...,...,...
519,totals,63.0,0.01,2024-05-28 21:00:48,9g5jXf74UWyXEJ4BZJ8gVp2ZJzG9bgPVijCtuUrWvv5DWH...,0.00,221.51,N/A
520,aliens69,54.0,0.01,2024-05-28 21:00:48,9gyKCPYkaBJp7z8NxxCygjwB6u9GLudiakUEUPpZ1bjhbJ...,0.00,258.43,N/A
521,totals,54.0,0.01,2024-05-28 21:00:48,9gyKCPYkaBJp7z8NxxCygjwB6u9GLudiakUEUPpZ1bjhbJ...,0.00,258.43,N/A
522,,84.0,0.02,2024-05-28 21:00:48,9haAysnicciRTb8Qexr3Qogrv1HwDk7AUKvoQkeSFnNMj3...,0.00,166.13,N/A
523,totals,84.0,0.02,2024-05-28 21:00:48,9haAysnicciRTb8Qexr3Qogrv1HwDk7AUKvoQkeSFnNMj3...,0.00,166.13,N/A

In [11]:
db_sync.db.create_table('performance',db_sync.performance_headers)
db_sync.db.fetch_data('performance')

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:265: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

,worker,hashrate,shares_per_second,created,miner,insert_time_stamp
0,totals,156.12,0.03,2024-05-28 12:00:00,9fs1QU7tsDvYNo1aVmMManemdF5Ud2QLavCTFABP3Smm3H...,None
1,totals,163.56,0.04,2024-05-28 13:00:00,9fs1QU7tsDvYNo1aVmMManemdF5Ud2QLavCTFABP3Smm3H...,None
2,,152.86,0.03,2024-05-28 14:00:00,9fs1QU7tsDvYNo1aVmMManemdF5Ud2QLavCTFABP3Smm3H...,None
3,totals,152.86,0.03,2024-05-28 14:00:00,9fs1QU7tsDvYNo1aVmMManemdF5Ud2QLavCTFABP3Smm3H...,None
4,,144.08,0.03,2024-05-28 15:00:00,9fs1QU7tsDvYNo1aVmMManemdF5Ud2QLavCTFABP3Smm3H...,None
...,...,...,...,...,...,...
3958,Rig1,632.37,0.07,2024-05-28 13:00:00,9gW4BxS6x8pF7BVMsE2VPpKTEHaDB9Nw1mp6MEpn5MWAmX...,None
3959,totals,686.06,0.08,2024-05-28 13:00:00,9gW4BxS6x8pF7BVMsE2VPpKTEHaDB9Nw1mp6MEpn5MWAmX...,None
3960,RIG_luc,65.21,0.01,2024-05-28 14:00:00,9gW4BxS6x8pF7BVMsE2VPpKTEHaDB9Nw1mp6MEpn5MWAmX...,None
3961,Rig1,482.74,0.07,2024-05-28 14:00:00,9gW4BxS6x8pF7BVMsE2VPpKTEHaDB9Nw1mp6MEpn5MWAmX...,None
3962,totals,547.95,0.08,2024-05-28 14:00:00,9gW4BxS6x8pF7BVMsE2VPpKTEHaDB9Nw1mp6MEpn5MWAmX...,None

In [10]:
flag = db_sync.__create_table__()
flag

True

In [11]:
get_size_and_tables()

8689 kB

In [12]:
init_db()

intializing DB
Connecting to DB instance
connected
tables created
UPDATED STATS TABLE SUCCESFULLY
UPDATED BLOCK TABLE SUCCESFULLY

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:269: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

no live data for miner 9hwEKqgW4XjRi7uYjRcsZHiRiuNT3dMHsR3J75BNSrGDQyKuz8Q
no live data for miner 9fmniVfPjpbcxoWA5n4SQvLPDzaNrtasHn7Jn7CLa57oinh1rtW
UPDATED LIVE WORK, PERFORMANCE, AND PAYMENT TABLES SUCCESFULLY
complete 9361 kB

In [13]:
get_size_and_tables()

9361 kB

In [14]:
val = 'qx3090-9fYvQMsMN3NNaw33cAFnRdyHy1DpxtxfADvGqUV3ocLptw4HpcP'
len(val)

58

In [15]:
update_pool_stats()

Connecting to DB instance
connected
UPDATED STATS TABLE SUCCESFULLY

In [19]:
update_blocks_and_live_workers()

Connecting to DB instance
connected
UPDATED BLOCK TABLE SUCCESFULLY

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:269: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

no live data for miner 9hwEKqgW4XjRi7uYjRcsZHiRiuNT3dMHsR3J75BNSrGDQyKuz8Q
no live data for miner 9fmniVfPjpbcxoWA5n4SQvLPDzaNrtasHn7Jn7CLa57oinh1rtW
UPDATED LIVE WORK, PERFORMANCE, AND PAYMENT TABLES SUCCESFULLY

In [17]:
update_payment_and_performance()

Connecting to DB instance
connected

/home/whaleshark/Documents/ergo/sigma-dashboard/utils/db_util.py:269: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, self.conn)

UPDATED LIVE WORK, PERFORMANCE, AND PAYMENT TABLES SUCCESFULLY

In [18]:
get_size_and_tables()

9761 kB